name:        'GoTSRPC Verify'
description: 'Verify if the generated code is valid'
inputs:
  target: # id of input
    description: 'Target file to generate GoTSRPC with'
    required:    true
    default:     'gotsrpc.yaml'
outputs:
  diff: # id of output
    description: 'The diff that was generated'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
